## This is a configuration file encompassing all the parameters needed to 
## execute the HMP2 AnADAMA2 analysis pipelines.

###################
# BASE PARAMETERS #
###################

base: &base
    # It seems like a lot of the sequences handled by the Broad are dropped
    # in the following directory.
    broad_sequence_dir: /seq/picard_aggregation

    # Next comes up the directories where our AnADAMA2 pipelines will pull and
    # deposit files to.        
    deposition_dir: /seq/ibdmdb/carze_test/data_deposition
    processing_dir: /seq/ibdmdb/carze_test/processing
    public_dir: /seq/ibdmdb/carze_test/public/

    # Databases used by the various different workflows. 
    # TODO: Move these to a centralized location
    databases:
        gg_usearch: /seq/ibdmdb/centos6/var/lib/gg_13_5_otus/rep_set/97_otus.udb
        gg_taxonomy: /seq/ibdmdb/centos6/var/lib/gg_13_5_otus/taxonomy/97_otu_taxonomy.txt
        gg_fasta: /seq/ibdmdb/centos6/var/lib/gg_13_5_otus/rep_set/97_otus.fasta
        chimera: /seq/ibdmdb/centos6/var/lib/uchime/gold.fa
        copy_num: /seq/ibdmdb/centos6/picrust-1.0.0/picrust/data/16S_13_5_precalculated.tab.gz        
        knead_dna: /seq/ibdmdb/centos6/var/lib/Homo_sapiens_Bowtie2_v0.1
        knead_rna: /seq/ibdmdb/centos6/var/lib/mrna
        knead_six: /seq/ibdmdb/centos6/var/lib/silva-119-1_SSURef_nr99
        humann2_nt: /seq/ibdmdb/centos6/var/lib/humann2/chocophlan
        humann2_p: /seq/ibdmdb/centos6/var/lib/humann2/uniref

############################
# PER-DATATYPE  PARAMETERS #
############################

proteomics: &proteomics
    <<: *base
    
    output_ftypes:
        - _rollup.txt
        - .png        

wgs: &wgs
    <<: *base

    output_ftypes:
        - _tax.txt
        - .png
        - .merged.tsv
        - .tar.bz2
        - .biom          

16S: &16S
    <<: *base

mtx: &mtx
    <<: *base

############################
#        METADATA          #
############################

## The parameters below are required by the HMP2 metadata curation pipelines.
metadata: &metadata
    <<: *base

    ## The list below defines the allowable data types that the metadata 
    ## pipeline should accept.
    data_types:
        - amplicon
        - proteomics
        - metagenomics
        - metatranscriptomics

    ## The cutplace CID files to use against our metadata files.
    validators:
        - studytrax: config/validation/studytrax.cid
        - broad_datasheet: config/validation/broad.cid
