## This is a configuration file encompassing all the parameters needed to 
## execute the HMP2 AnADAMA2 analysis pipelines.

###################
# BASE PARAMETERS #
###################

base: &base
    # It seems like a lot of the sequences handled by the Broad are dropped
    # in the following directory.
    broad_sequence_dir: /seq/picard_aggregation

    # Next comes up the directories where our AnADAMA2 pipelines will pull and
    # deposit files to.        
    deposition_dir: /seq/ibdmdb/carze_test/data_deposition
    processing_dir: /seq/ibdmdb/carze_test/processing
    public_dir: /seq/ibdmdb/carze_test/public/

    # Databases used by the various different workflows. 
    # TODO: Move these to a centralized location
    databases:
        gg_usearch: /seq/ibdmdb/centos6/var/lib/gg_13_5_otus/rep_set/97_otus.udb
        gg_taxonomy: /seq/ibdmdb/centos6/var/lib/gg_13_5_otus/taxonomy/97_otu_taxonomy.txt
        gg_fasta: /seq/ibdmdb/centos6/var/lib/gg_13_5_otus/rep_set/97_otus.fasta
        chimera: /seq/ibdmdb/centos6/var/lib/uchime/gold.fa
        copy_num: /seq/ibdmdb/centos6/picrust-1.0.0/picrust/data/16S_13_5_precalculated.tab.gz        
        knead_dna: /seq/ibdmdb/centos6/var/lib/Homo_sapiens_Bowtie2_v0.1
        knead_mtx: /seq/ibdmdb/centos6/var/lib/mrna
        knead_rrna: /seq/ibdmdb/centos6/var/lib/silva-119-1_SSURef_nr99
        humann2_nt: /seq/ibdmdb/centos6/var/lib/humann2/chocophlan
        humann2_p: /seq/ibdmdb/centos6/var/lib/humann2/uniref

############################
# PER-DATATYPE  PARAMETERS #
############################

proteomics: &proteomics
    <<: *base
    
    output_ftypes:
        - _rollup.txt
        - .png        

mgx: &mgx
    <<: *base

    output_ftypes:
        - _tax.txt
        - .png
        - .merged.tsv
        - .tar.bz2
        - .biom          

16S: &16S
    <<: *base

mtx: &mtx
    <<: *base

############################
#        METADATA          #
############################

## The parameters below are required by the HMP2 metadata curation pipelines.
metadata: &metadata
    <<: *base

    ## The list below defines the allowable data types that the metadata 
    ## pipeline should accept.
    input_extensions:
        - .bam
        - .raw

    drop_cols:
        - Sheet Name
        - Subject
        - Status
        - Receipt Status
        - "Collection #"
        - Actual Date of Receipt
        - Parent Sample A
        - Parent Sample B
        - DNA/RNA
        - DNA/RNA mass
        - DNA/RNA status
        - MbX
        - MBX mass
        - MBX status
        - MBX leak?
        - MBX Volume Recorded
        - Viromics
        - Viromics mass
        - Viromics status
        - Viromics Selection
        - Storage 
        - Storage mass
        - Storage status
        - Storage Sample Selection
        - Fecal Cal Selection
        - Fecal Calprotectin
        - Fecal Cal mass
        - Fecal Cal status
        - Proteomics
        - Proteomics mass
        - Proteomics status
        - Prot. Sample Selection
        - Site
        - sample_ids
        - Dataset
        - State
        - Job
        - Tool
        - Parameter_File
        - Settings_File
        - Instrument
        - Experiment
        - Campaign
        - Organism
        - Organism DB
        - Protein Collection List
        - Protein Options
        - Comment
        - Results Folder
        - Folder
        - Dataset_ID
        - Dataset_Created
        - Job_Finish
        - Dataset_Rating
        - Separation_Type
        - Dataset_Type
        - Request_ID
        - Site/Sub/Coll

    col_order:
        - Project
        - External ID
        - Participant ID
        - Site/Sub/Coll ID
        - data_type
        - week_num
        - interval_days
        - visit_num
        - Research Project
        - PDO Number
        - GSSR IDs
        - Product
        - LCSET
        - Aggregated Lanes
        - WR ID
        - "# Lanes in Aggregation"
        - Total Reads

    ## The cutplace CID files to use against our metadata files.
    validators:
        - studytrax: config/validation/studytrax.cid
        - broad_datasheet: config/validation/broad.cid

############################
#           DCC            #
############################

## The paremeters below are used when submitting metadata or data files to 
## The DCC.
dcc: &dcc
    <<: *base

    username: carze
    password: fishnet-socket-dolphin-can

    namespace: ihmp
    project_id: iHMP

    metadata_id_mappings:
        proteomics: "Tube B:Proteomics"
        wgs: External ID
        16s: External ID
        mtx: External ID

    metadata_to_tracking_mapping: "Sample ID: Tube B (No preservative)"
    tracking_id_col: Parent Sample B       
    
    # Each of the Prep's and data files has an affiliated study title which
    # is actually diffeernt from the Study object name...
    data_study: ibd
    
    race_map:
        Other: ethnic_other
        "More than one race": ethnic_other
        "Black or African American": african_american
        White: caucasian

    study:
        name: Inflammatory Bowel Disease Multi-omics Database (IBDMDB)
        subtype: ibd
        description: >-
            A new three-year "multi-omic" study investigating the roles played
            by microbes and their interactions with the human body.
        contact: "Curtis Huttenhower"
        center: Broad Institute
        tags:
            - "bioproject:PRJNA306874"

    sample:
        body_site: stool
        fma_body_site: "FMA:64183"
        mixs:            
            biome: "ENVO:00009003"
            body_product: stool
            material: "ENVO:5792"
            feature: "ENVO:00002003"
            lat_lon: "+42.363664 -71.069230"
            geo_loc_name: United States of America
            env_package: "Human-associated"
    
    16s:
        prep_id: 1
        library_method_text: >-
            Samples are diluted and run in a 30 cycle PCR that specifically
            amplifies the V4 region of the 16S ribosomal subunit, with the
            primers making use of the highly conserved regions on either
            side. PCR primers are barcoded by well, in a dual plate format,
            for a total of 192 available barcodes. Samples are quantified
            using the caliper, and then pooled together. Finally, the pooled
            sample is cleaned up and selected for size by using a combination
            of purification columns and a Pippen Prep SAGE protocol, and
            handed off for MiSeq.

    wgs:
        library_method_text: >-
            Metagenomic DNA samples were quantified by Quant-iT PicoGreen dsDNA
            Assay (Life Technologies) and normalized to a concentration of
            50 pg/microliter. Illumina sequencing libraries were prepared from
            100-250 pg DNA using the Nextera XT DNA Library Preparation
            kit (Illumina) according to the manufacturer's recommended
            protocol, with reaction volumes scaled accordingly. Batches of
            24, 48, or 96 libraries were pooled by transferring equal
            volumes of each library using a Labcyte Echo 550 liquid
            handler. Insert sizes and concentrations for each pooled
            library were determined using an Agilent Bioanalyzer DNA 1000
            kit (Agilent Technologies).
        prep_id: 2
        sequencing_contact: "tpoon@broadintitute.org"
        sequencing_center: Broad Institute
        ncbi_taxon_id: 408170 
        lib_layout: fragment
        lib_selection: Random
        prep_comment: Broad IBDMDB default WGS dna prep
        seq_comment: Raw WGS Sequence set 
        storage_duration: 365
        sequencer_model: Illumina HiSeq 2000

    mtx:
        library_method_text: >-
            Our method, RNAtag-Seq, utilizes a molecular barcoding strategy
            that generates multiple libraries in a single reaction, lowers
            labor and reagent costs per sample, and produces data on
            prokaryotic and eukaryotic samples that are comparable to
            those generated by traditional strand-specific RNA-seq
            approaches.  Barcoding in RNAtag-Seq is achieved through
            direct ligation of adaptors to RNA, enabling high quality,
            strand-specific, quantitative sequencing of full-length
            transcripts in diverse prokaryotic and eukaryotic species.
        prep_id: 3
        sequencing_contact: "tpoon@broadintitute.org"
        sequencing_center: Broad Institute
        ncbi_taxon_id: 408170 
        lib_layout: fragment
        lib_selection: Random
        prep_comment: Broad IBDMDB default Microbe Transcriptomics dna prep
        seq_comment: Raw Microbe Transcriptomics Sequence set 
        storage_duration: 365
        sequencer_model: Illumina HiSeq 2000

    proteomics:
        assay:
            center: PNNL
            contact: "White, Richard A <richard.white@pnnl.gov"
            storage_duration: 365
            experiment_type: "PRIDE:0000429, Shotgun proteomics"
            protocol_steps: ""
            species: ""
            tissue: ""
            title: ""
        proteome:                
            analyzer: QExactive
            detector: QExactive
            instrument_name: QExactive
            pepid_format: List
            processing_method: MSGF+
            protid_format: List
            protmod_format: NA
            protocol_name: NA
            search_engine: MSGF+
            software: MSGF+
            source: MSGF+
            spectra_format: .raw
            study: ibd
            subtype: host
            comment: IBDMDB
            title: IBDMDB
            short_label: NA
            
