## Configuration parameters required to handle upload of metadata, sequence 
## data or analysis products to the DCC.

username: DCC_USERNAME
password: DCC_PASSWORD

namespace: ihmp
project_id: iHMP

metadata_id_mappings:
  MBX: "Tube B:Proteomics"
  MGX: External ID
  16S: External ID
  MTX: External ID
  TX: External ID

datatype_mapping:
  MGX: metagenomics
  MBX: metabolomics
  MPX: proteomics
  16S: amplicon
  MTX: metatranscriptomics
  TX: host_transcriptomics

metadata_to_tracking_mapping: "Sample ID: Tube B (No preservative)"
tracking_id_col: Parent Sample B       

# Each of the Prep's and data files has an affiliated study title which
# is actually diffeernt from the Study object name...
data_study: ibd

race_map:
  Other: ethnic_other
  "More than one race": ethnic_other
  "Black or African American": african_american
  White: caucasian
  "American Indian or Alaska Native": american_indian_or_alaska_native

study:
  name: Inflammatory Bowel Disease Multi-omics Database (IBDMDB)
  subtype: ibd
  description: >-
      A new three-year "multi-omic" study investigating the roles played
      by microbes and their interactions with the human body.
  contact: "Curtis Huttenhower"
  center: Broad Institute
  tags:
      - "bioproject:PRJNA306874"

sample:
  body_site_map:
    'Sigmoid Colon': 'sigmoid_colon'
    'Descending (left-sided) colon': 'descending_colon'
    'Cecum': 'appendix'
    'Ascending (right-sided) colon': 'ascending_colon'
    'Transverse colon': 'transverse_colon'
    'Rectum': 'rectal'
    'Terminal ileum': 'terminal_ileum'
    'Ileum': 'ileum'
  fma_body_map:
    'sigmoid_colon': 'FMA:14548'
    'descending_colon': 'FMA:14547'
    'appendix': 'FMA:14541'
    'ascending_colon': 'FMA:14545'
    'transverse_colon': 'FMA:14546'
    'rectal': 'FMA:14544'
    'terminal_ileum': 'FMA:14966'
    'ileum': 'FMA:7208'
    'stool': 'FMA:64183'
  mixs:            
      project_name: "iHMP"
      samp_size: "N/A"
      samp_collect_device: "stool collection"
      biome: "ENVO:00009003"
      material: "ENVO:5792"
      feature: "ENVO:00002003"
      lat_lon: "+42.363664 -71.069230"
      geo_loc_name: United States of America
      env_package: "Human-associated"
      rel_to_oxygen: "N/A"

16S:
  prep_id: 1
  library_method_text: >-
      Samples are diluted and run in a 30 cycle PCR that specifically
      amplifies the V4 region of the 16S ribosomal subunit, with the
      primers making use of the highly conserved regions on either
      side. PCR primers are barcoded by well, in a dual plate format,
      for a total of 192 available barcodes. Samples are quantified
      using the caliper, and then pooled together. Finally, the pooled
      sample is cleaned up and selected for size by using a combination
      of purification columns and a Pippen Prep SAGE protocol, and
      handed off for MiSeq.

MGX:
  assay:
    sequencing_center: Sequencing Center
    sequencing_contact: "contact@email.com"
    ncbi_taxon_id: 408170 
    lib_layout: fragment
    lib_selection: Random
    storage_duration: 365
    comment: IBDMDB
  mims:
    biome: "terrestrial biome [ENVO:00000446]"
    geo_loc_name: "United States of America"
    investigation_type: "metagenome"
    lat_lon: Unknown
    seq_method: "Illumina HiSeq 2000"
    env_package': 'human-associated'
    library_const_meth: >-
        Metagenomic DNA samples were quantified by Quant-iT PicoGreen dsDNA
        Assay (Life Technologies) and normalized to a concentration of
        50 pg/microliter. Illumina sequencing libraries were prepared from
        100-250 pg DNA using the Nextera XT DNA Library Preparation
        kit (Illumina) according to the manufacturer's recommended
        protocol, with reaction volumes scaled accordingly. Batches of
        24, 48, or 96 libraries were pooled by transferring equal
        volumes of each library using a Labcyte Echo 550 liquid
        handler. Insert sizes and concentrations for each pooled
        library were determined using an Agilent Bioanalyzer DNA 1000
        kit (Agilent Technologies).
  metagenome:
    study: ibd
    exp_length: 0
    format: fastq
    sequence_type: nucleotide
    format_doc: "https://en.wikipedia.org/wiki/FASTQ_format"
    seq_model: ""
    comment: IBDMDB
  abundance_matrix:
    comment: ""
    format: "biom"

TX:
  assay:
      sequencing_center: Center Name
      sequencing_contact: "contact@email.com"
      lib_layout: ""
      lib_selection: ""
      ncbi_taxon_id: 9606
      storage_duration: ""
  host_transcriptome:
      study: ibd
      format: fastq
      format_doc: "https://en.wikipedia.org/wiki/FASTQ_format"
      sequence_type: "nucleotide"
      seq_model: ""
      exp_length: 0
      comment: IBDMDB

MTX:
  library_method_text: >-
      Our method, RNAtag-Seq, utilizes a molecular barcoding strategy
      that generates multiple libraries in a single reaction, lowers
      labor and reagent costs per sample, and produces data on
      prokaryotic and eukaryotic samples that are comparable to
      those generated by traditional strand-specific RNA-seq
      approaches.  Barcoding in RNAtag-Seq is achieved through
      direct ligation of adaptors to RNA, enabling high quality,
      strand-specific, quantitative sequencing of full-length
      transcripts in diverse prokaryotic and eukaryotic species.
  prep_id: 3
  sequencing_contact: "contact@email.com"
  sequencing_center: Sequencing Center
  ncbi_taxon_id: 408170 
  lib_layout: fragment
  lib_selection: Random
  prep_comment: IBDMDB default Microbe Transcriptomics dna prep
  seq_comment: Raw Microbe Transcriptomics Sequence set 
  storage_duration: 365
  sequencer_model: Illumina HiSeq 2000

MBX:
  assay:
      center: Center Name
      contact: "contact@email.com"
      storage_duration: 365
      experiment_type: "PRIDE:0000429, Shotgun proteomics"
      protocol_steps: ""
      species: ""
      tissue: ""
      title: ""
  proteome:                
      analyzer: QExactive
      detector: QExactive
      instrument_name: QExactive
      exp_description: ""
      data_processing_protocol: ""
      #pepid_format: List
      processing_method: MSGF+
      #protid_format: List
      #protmod_format: NA
      protocol_name: NA
      search_engine: MSGF+
      software: MSGF+
      source: MSGF+
      #spectra_format: .raw
      study: ibd
      #subtype: host
      comment: IBDMDB
      title: IBDMDB
      short_label: NA
      