## Configuration parameters required to handle upload of metadata, sequence 
## data or analysis products to the DCC.

username: DCC_USERNAME
password: DCC_PASSWORD

namespace: ihmp
project_id: iHMP

metadata_id_mappings:
  MBX: "Tube B:Proteomics"
  MGX: External ID
  16S: External ID
  MTX: External ID
  HTX: External ID
  HG: External ID
  MVX: Viromics
  RRBS: External ID
  SER: External ID

datatype_mapping:
  MGX: metagenomics
  MBX: metabolomics
  MPX: proteomics
  16S: amplicon
  MTX: metatranscriptomics
  HTX: host_transcriptomics
  HG: host_genome
  RRBS: methylome
  SER: serology
  16SBP: biopsy_16S

nonstool_datatype:
  - HTX
  - HG
  - RRBS
  - SER
  - 16SBP

metadata_to_tracking_mapping: "Sample ID: Tube B (No preservative)"
tracking_id_col: Parent Sample B       

# Each of the Prep's and data files has an affiliated study title which
# is actually diffeernt from the Study object name...
data_study: ibd

race_map:
  Other: ethnic_other
  "More than one race": ethnic_other
  "Black or African American": african_american
  White: caucasian
  "American Indian or Alaska Native": american_indian_or_alaska_native

disease_map:
  uc: "ulcerative colitis"
  cd: "Crohn's disease"
  nonIBD: "Non-IBD"

study:
  name: Inflammatory Bowel Disease Multi-omics Database (IBDMDB)
  subtype: ibd
  description: >-
      A new three-year "multi-omic" study investigating the roles played
      by microbes and their interactions with the human body.
  contact: "Curtis Huttenhower"
  center: Broad Institute
  tags:
      - "bioproject:PRJNA306874"

sample:
  body_site_map:
    'Sigmoid Colon': 'sigmoid_colon'
    'Descending (left-sided) colon': 'descending_colon'
    'Cecum': 'appendix'
    'Ascending (right-sided) colon': 'ascending_colon'
    'Transverse colon': 'transverse_colon'
    'Rectum': 'rectal'
    'Terminal ileum': 'terminal_ileum'
    'Ileum': 'ileum'
  fma_body_map:
    'sigmoid_colon': 'FMA:14548'
    'descending_colon': 'FMA:14547'
    'appendix': 'FMA:14541'
    'ascending_colon': 'FMA:14545'
    'transverse_colon': 'FMA:14546'
    'rectal': 'FMA:14544'
    'terminal_ileum': 'FMA:14966'
    'ileum': 'FMA:7208'
    'stool': 'FMA:64183'
  mixs:            
      project_name: "iHMP"
      samp_size: "N/A"
      samp_collect_device: "stool collection"
      biome: "ENVO:00009003"
      material: "ENVO:5792"
      feature: "ENVO:00002003"
      lat_lon: "+42.363664 -71.069230"
      geo_loc_name: United States of America
      env_package: "Human-associated"
      rel_to_oxygen: "N/A"

subject_attribute:
  meds_cols:
    - "Lomotil"
    - "Imodium"
    - "DTO"
    - "Asacol (mesalamine)"
    - "Pentasa (mesalamine)"
    - "Lialda (mesalamine)"
    - "Apriso (mesalamine)"
    - "Colozal (balasalizide)"
    - "Sulfasalizine (Azulfidine)"
    - "Dipentum (olsalazine)"
    - "Rowasa enemas (mesalamine enemas)"
    - "Canasa suppositories (mesalamine suppositories)"
    - "Flagyl (Metronidazole)"
    - "Cipro (Ciprofloxin)"
    - "Xifaxin (rifaxamin)"
    - "Levaquin"
    - "Prednisone"
    - "Entocort (Budesonide)"
    - "Solumedrol (Medrol)"
    - "IV steroids"
    - "Cortenemas, Cortifoam, Proctofoam"
    - "Azathioprine (Imuran, Azasan)"
    - "Methotrexate"
    - "Mercaptopurine (Purinethol, 6MP)"
    - "VSL #3"
    - "FOS"
    - "Remicade (Infliximab)"
    - "Humira (Adalimumab)"
    - "Cimzia (Certlizumab)"
    - "Tysabri (Natalizumab)"
    - "Other current IBD medications"
  col_map:
    occupation: "Occupation"
    diabetes: "Type I Diabetes (Juvenile Diabetes)"
    asthma: "Asthma"
    cad: "Myocarditis"
    father: "Father"
    mother: "Mother"
    siblings: "Does the subject have a sibling with IBD?"
    education: "Education Level"
    disease_name: diagnosis
    alcohol: "Alcohol (beer, brandy, spirits, hard liquor, wine, aperitif, etc.)"
    tobacco: "smoking status"

visit_attribute:
  meds_stopped_cols:
    - "Reason for stopping lomotil:"
    - "Reason for stopping Imodium:"
    - "Reason for stopping Asacol:"
    - "Reason for stopping Pentasa:"
    - "Reason for stopping Lialda:"
    - "Reason for stopping Apriso:"
    - "Reason for stopping Colozal:"
    - "Reason for stopping Sulfasalazine:"
    - "Reason for stopping Dipentum:"
    - "Reason for stopping rowasa enemas:"
    - "Reason for stopping canasa suppositories:"
  cancer_cols:
    - "Cancer - breast"
    - "Cancer - cholangiocarcinoma"
    - "Cancer - colon or rectum"
    - "Cancer - Hodgkin's lymphoma"
    - "Cancer - liver"
    - "Cancer - lung"
    - "Cancer - lymphoma (not otherwise specified)"
    - "Cancer - Non-Hodkin's lymphoma"
    - "Cancer - ovarian"
    - "Cancer - prostate"
  desc_map:
    cd: "An intestinal disease that involves inflammation located_in intestine."
    uc: >- 
      A colitis that is predominantly confined to the mucosa located_in colon 
      and includes characteristic ulcers, or open sores.
  xref_map:
    cd:
      DO: "DOID:8778"
      NCI: "NCI:C35211"
      MESH: "MESH:D003424"
      UML: "UMLS_CUI:C0156147"
    uc:
      DO: "DOID:8577"
      NCI: "NCI:C2952"
      MESH: "MESH:D003093"
      UML: "UMLS_CUI:C0009324"
  col_map:
    disease_name: diagnosis
    abdominal_pain: "Abdominal pain"
    arthralgia: "Arthralgia"
    age: consent_age
    bowel_day: "Bowel frequency during the day"
    bowel_night: "Bowel frequency during the night"
    stool_blood: "Blood in the stool"
    stool_sof: "Number of liquid or very soft stools in the past 24 hours:"
    urgency_def: "Urgency of defecation"
    pregnant: "Subject is pregnant:"
    chemo: "Chemotherapy"
    immunosupp: "Immunosuppressants (e.g. oral corticosteroids)"
    abx: "Antibiotics"
    alcohol: "Alcohol (beer, brandy, spirits, hard liquor, wine, aperitif, etc.)"
    soda: "Soft drinks, tea or coffee with sugar (corn syrup, maple syrup, cane sugar, etc)"
    beans: "Beans (tofu, soy, soy burgers, lentils, Mexican beans, lima beans etc)"
    dairy: "Dairy (milk, cream, ice cream, cheese, cream cheese)"
    grains: "Whole grains (wheat, oats, brown rice, rye, quinoa, wheat bread, wheat pasta)"
    eggs: Eggs
    fish: "Fish (fish nuggets, breaded fish, fish cakes, salmon, tuna, etc.)"
    fruit: "Fruits (no juice) (Apples, raisins, bananas, oranges, strawberries, blueberries"
    juice: "Fruit juice (orange, apple, cranberry, prune etc.)"
    meat_red: "Red meat (beef, hamburger, pork, lamb)"
    meat_white: "White meat (chicken, turkey, etc.)"
    probiotic: "Probiotic"
    shellfish: "Shellfish (shrimp, lobster, scallops, etc.)"
    sweets: "Sweets (pies, jam, chocolate, cake, cookies, etc.)"
    veg: "Vegetables (salad, tomatoes, onions, greens, carrots, peppers, green beans, etc)"
    water: Water
    yogurt: "Yogurt or other foods containing active bacterial cultures (kefir, sauerkraut)"

16S:
  prep_id: 1
  library_method_text: >-
      Samples are diluted and run in a 30 cycle PCR that specifically
      amplifies the V4 region of the 16S ribosomal subunit, with the
      primers making use of the highly conserved regions on either
      side. PCR primers are barcoded by well, in a dual plate format,
      for a total of 192 available barcodes. Samples are quantified
      using the caliper, and then pooled together. Finally, the pooled
      sample is cleaned up and selected for size by using a combination
      of purification columns and a Pippen Prep SAGE protocol, and
      handed off for MiSeq.

MGX:
  assay:
    sequencing_center: Sequencing Center
    sequencing_contact: "contact@email.com"
    ncbi_taxon_id: 408170 
    lib_layout: fragment
    lib_selection: Random
    storage_duration: 365
    comment: IBDMDB
  mims:
    biome: "terrestrial biome [ENVO:00000446]"
    geo_loc_name: "United States of America"
    investigation_type: "metagenome"
    lat_lon: Unknown
    seq_meth: "Illumina HiSeq 2000"
    env_package: 'human-associated'
    lib_const_meth: >-
        Metagenomic DNA samples were quantified by Quant-iT PicoGreen dsDNA
        Assay (Life Technologies) and normalized to a concentration of
        50 pg/microliter. Illumina sequencing libraries were prepared from
        100-250 pg DNA using the Nextera XT DNA Library Preparation
        kit (Illumina) according to the manufacturer's recommended
        protocol, with reaction volumes scaled accordingly. Batches of
        24, 48, or 96 libraries were pooled by transferring equal
        volumes of each library using a Labcyte Echo 550 liquid
        handler. Insert sizes and concentrations for each pooled
        library were determined using an Agilent Bioanalyzer DNA 1000
        kit (Agilent Technologies).
  metagenome:
    study: ibd
    exp_length: 0
    format: fastq
    sequence_type: nucleotide
    format_doc: "https://en.wikipedia.org/wiki/FASTQ_format"
    seq_model: ""
    comment: IBDMDB
  abundance_matrix:
    comment: ""
    format: "biom"

HTX:
  assay:
    sequencing_center: Center Name
    sequencing_contact: "contact@email.com"
    lib_layout: ""
    lib_selection: ""
    ncbi_taxon_id: "9606"
    storage_duration: 0
  mims:
    geo_loc_name: "United States of America"
    lat_lon: Unknown
    biome: "terrestrial biome [ENVO:00000446]"
    feature: "human-associated habitat [ENVO:00009003]"
    env_package: human-associated
    collection_date: Unknown
    seq_meth: "Sequencing by Synthesis"
    lib_const_meth: >-
        Total RNA was quantified using the Quant-iT RiboGreen RNA Assay Kit
        and normalized to 5ng/ul. Following plating, 2 uL of ERCC controls
        (using a 1:1000 dilution) were spiked into each sample.  An aliquot of
        200ng for each sample was transferred into library preparation which was
        an automated variant of the Illumina TruSeq Stranded mRNA Sample Preparation
        Kit.  This method preserves strand orientation of the RNA transcript. It uses
        oligo dT beads to select mRNA from the total RNA sample. It is followed by heat
        fragmentation and cDNA synthesis from the RNA template. The resultant 500bp cDNA
        then goes through library preparation (end repair, base A addition, adapter ligation,
        and enrichment) using Broad designed indexed adapters substituted in for multiplexing.
        After enrichment the libraries were quantified using Quant-iT PicoGreen (1:200 dilution).
        After normalizing samples to 5 ng/uL, the set was pooled and quantified using the KAPA
        Library Quantification Kit for Illumina Sequencing Platforms.  The entire process is in
        96-well format and all pipetting is done by either Agilent Bravo or Hamilton Starlet.
  host_transcriptome:
    study: ibd
    format: fastq
    format_doc: "https://en.wikipedia.org/wiki/FASTQ_format"
    sequence_type: "nucleotide"
    seq_model: ""
    exp_length: 0
    comment: IBDMDB

HG: 
  assay:
    sequencing_center: Center Name
    sequencing_contact: "contact@email.com"
    lib_layout: ""
    lib_selection: ""
    ncbi_taxon_id: "9606"
    storage_duration: 0
  mims:
    geo_loc_name: "United States of America"
    lat_lon: Unknown
    biome: "terrestrial biome [ENVO:00000446]"
    feature: "human-associated habitat [ENVO:00009003]"
    env_package: human-associated
    collection_date: Unknown
    seq_meth: "Sequencing by Synthesis"
    lib_const_meth: >-
        Library construction was performed as described by Fisher et al. with some slight 
        modifications. Initial genomic DNA input into shearing was reduced from 3µg to 50ng 
        in 10µL of solution and enzymatically sheared. In addition, for adapter ligation,
        dual-indexed Illumina paired end adapters were replaced with palindromic forked 
        adapters with unique 8 base index sequences embedded within the adapter and added
        to each end.

        In-solution hybrid selection was performed using the Illumina Rapid Capture Exome 
        enrichment kit with 38Mb target erritory (29Mb baited). The targeted region includes 
        98.3% of the intervals in the Refseq exome database. Dual-indexed libraries are 
        pooled into groups of up to 96 samples prior to hybridization. The liquid handling 
        is automated on a Hamilton Starlet. The enriched library pools are quantified via 
        PicoGreen after elution from  streptavadin beads and then normalized to a range 
        compatible with sequencing template denature protocols.

        Following sample preparation, the libraries prepared using forked, indexed adapters
        were quantified using quantitative PCR (purchased from KAPA biosystems), 
        normalized to 2 nM using the Hamilton Starlet Liquid Handling system, and pooled
        by equal volume using the Hamilton Starlet Liquid Handling system. Pools were 
        then denatured using 0.1 N NaOH. Denatured samples were diluted into strip 
        tubes using the the Hamilton Starlet Liquid Handling system.
  host_genome:
    study: ibd
    format: fastq
    format_doc: "https://en.wikipedia.org/wiki/FASTQ_format"
    sequence_type: "nucleotide"
    exp_length: 0
    comment: IBDMDB

RRBS:
  assay:
    sequencing_center: Center Name
    sequencing_contact: "contact@email.com"
    lib_layout: ""
    lib_selection: ""
    ncbi_taxon_id: 9606
    storage_duration: ""
  methylome:
    study: ibd
    format: fastq
    format_doc: "https://en.wikipedia.org/wiki/FASTQ_format"
    sequence_type: "nucleotide"
    exp_length: 0
    comment: IBDMDB
  abundance_matrix:
    comment: ""
    format: "table"    

SER:
  assay:
    sequencing_center: Center Name
    sequencing_contact: "contact@email.com"
    lib_layout: ""
    lib_selection: ""
    ncbi_taxon_id: 9606
    storage_duration: ""
  serology:
    study: ibd
    format: fastq
    format_doc: "https://en.wikipedia.org/wiki/FASTQ_format"
    sequence_type: "nucleotide"
    exp_length: 0
    comment: IBDMDB
  abundance_matrix:
    comment: ""
    format: "table"    

MTX:
  assay:
    sequencing_center: Sequencing Center
    sequencing_contact: "contact@email.com"
    ncbi_taxon_id: 408170 
    lib_layout: fragment
    lib_selection: Random
    storage_duration: "365"
    comment: IBDMDB
  mims:
    biome: "terrestrial biome [ENVO:00000446]"
    geo_loc_name: "United States of America"
    investigation_type: "metagenome"
    lat_lon: Unknown
    seq_meth: "Illumina HiSeq 2000"
    env_package: 'human-associated'
    lib_const_meth: >-
        Our method, RNAtag-Seq, utilizes a molecular barcoding strategy
        that generates multiple libraries in a single reaction, lowers
        labor and reagent costs per sample, and produces data on
        prokaryotic and eukaryotic samples that are comparable to
        those generated by traditional strand-specific RNA-seq
        approaches.  Barcoding in RNAtag-Seq is achieved through
        direct ligation of adaptors to RNA, enabling high quality,
        strand-specific, quantitative sequencing of full-length
        transcripts in diverse prokaryotic and eukaryotic species.
  metatranscriptome:
    study: ibd
    exp_length: 0
    format: fastq
    sequence_type: nucleotide
    format_doc: "https://en.wikipedia.org/wiki/FASTQ_format"
    seq_model: ""
    comment: IBDMDB
  abundance_matrix:
    comment: ""

MVX:
  assay:
    sequencing_center: Sequencing Center
    sequencing_contact: "contact@email.com"
    ncbi_taxon_id: "408170"
    lib_layout: fragment
    lib_selection: Random
    storage_duration: "365"
    comment: IBDMDB
  mims:
    biome: "terrestrial biome [ENVO:00000446]"
    geo_loc_name: "United States of America"
    investigation_type: "metagenome"
    lat_lon: Unknown
    seq_meth: "Illumina HiSeq 2000"
    env_package: 'human-associated'
    lib_const_meth: >-
        Metagenomic DNA samples were quantified by Quant-iT PicoGreen dsDNA
        Assay (Life Technologies) and normalized to a concentration of
        50 pg/microliter. Illumina sequencing libraries were prepared from
        100-250 pg DNA using the Nextera XT DNA Library Preparation
        kit (Illumina) according to the manufacturer's recommended
        protocol, with reaction volumes scaled accordingly. Batches of
        24, 48, or 96 libraries were pooled by transferring equal
        volumes of each library using a Labcyte Echo 550 liquid
        handler. Insert sizes and concentrations for each pooled
        library were determined using an Agilent Bioanalyzer DNA 1000
        kit (Agilent Technologies).
  virome:
    format: fastq
    format_doc: "https://en.wikipedia.org/wiki/FASTQ_format"
    study: ibd


MBX:
  assay:
      center: Center Name
      contact: "contact@email.com"
      storage_duration: 365
      experiment_type: "PRIDE:0000429, Shotgun proteomics"
      protocol_steps: ""
      species: ""
      tissue: ""
      title: ""
  proteome:                
      analyzer: QExactive
      detector: QExactive
      instrument_name: QExactive
      exp_description: ""
      data_processing_protocol: ""
      #pepid_format: List
      processing_method: MSGF+
      #protid_format: List
      #protmod_format: NA
      protocol_name: NA
      search_engine: MSGF+
      software: MSGF+
      source: MSGF+
      #spectra_format: .raw
      study: ibd
      #subtype: host
      comment: IBDMDB
      title: IBDMDB
      short_label: NA

