data_types:
    - amplicon
    - proteomics
    - metagenomics
    - metatranscriptomics

output_col_names:
	- Project'
	- External ID'
    - Participant ID'
    - Site/Sub/Coll ID'
    - date_type'
    - week_num'
    - interval_days'
    - visit_num'
    - Research Project'
    - PDO Number'
    - GSSR IDs'
    - Product'
    - LCSET'
    - Aggregated Lanes'
    - WR ID'
    - # Lanes in Aggregation'
    - Total Reads'

proteomics_upload_dir: /seq/ibdmdb/data_deposition/HMP2/Proteomics/1633/rschwager/ 

sources:
	studytrax_names: /seq/ibdmdb/data_deposition/HMP2/Metadata/json/hospital_mapping.csv
	studytrax_rows: /seq/ibdmdb/data_deposition/HMP2/Metadata/json/hospital.csv
    receipt_date_map: /seq/ibdmdb/data_deposition/HMP2/Metadata/json/receipt_date_map.json
	fecalcal_data: /seq/ibdmdb/data_deposition/HMP2/Metadata/json/fecalcal.csv
    age_map: /seq/ibdmdb/data_deposition/HMP2/Metadata/json/age_map.csv
    melanie_ordering: /seq/ibdmdb/data_deposition/HMP2/Metadata/json/melanie_order.csv
	mtx_pilot1: /seq/ibadmdb/data_deposition/HMP2/Metadata/json/Aggregated Picard Report for IBDMDB TagSeq_wCollabSampleID2.csv
	wgs_pilot1: /seq/ibdmdb/data_deposition/HMP2/Metadata/json/IBDMDB_PDO-5457_5458_WGS_SeqComplete_2.19.2015_wCollabSampleID2.csv
	sxs_pilot1: /seq/ibdmdb/data_deposition/HMP2/Metadata/json/IBDMDB_16S_PDO-4852_SeqComplete.csv
	wgs_pilot2: /seq/ibdmdb/data_deposition/HMP2/Metadata/json/IBDMDB_PilotII_WGS_SeqComplete_4.27.2016.csv
	prx_pilot1: /seq/ibdmdb/data_deposition/HMP2/Metadata/json/proteomics.csv"
